name: Waypoints
authors:
  - Md5Lukas
main: de.md5lukas.waypoints.WaypointsPlugin
loader: de.md5lukas.waypoints.DependencyYmlLoader
version: ${version}

website: https://github.com/Sytm/waypoints

api-version: ${apiVersion}
folia-supported: true

dependencies:
  server:
    Vault:
      load: BEFORE
      required: false
      join-classpath: true
    dynmap:
      load: BEFORE
      required: false
      join-classpath: true
    ProtocolLib:
      load: BEFORE
      required: false
      join-classpath: true
    squaremap:
      load: BEFORE
      required: false
      join-classpath: true
    BlueMap:
      load: BEFORE
      required: false
      join-classpath: true
    Pl3xMap:
      load: BEFORE
      required: false
      join-classpath: true

permissions:
  waypoints.*:
    default: op
    children:
      - waypoints.command.scripting
      - waypoints.command.use
      - waypoints.command.other
      - waypoints.command.statistics
      - waypoints.command.reload
      - waypoints.unlimited
      - waypoints.temporaryWaypoint
      - waypoints.modify.private
      - waypoints.modify.public
      - waypoints.modify.permission
      - waypoints.modify.anywhere
      - waypoints.teleport.private
      - waypoints.teleport.public
      - waypoints.teleport.permission
      - waypoints.tracking.enabled
      - waypoints.tracking.trackAll
      - waypoints.updateNotification

  waypoints.command.scripting: { }
  waypoints.command.use:
    default: true
  waypoints.command.other: { }
  waypoints.command.statistics: { }

  waypoints.unlimited: { }
  waypoints.temporaryWaypoint:
    default: true

  waypoints.modify.private:
    default: true
  waypoints.modify.public: { }
  waypoints.modify.permission: { }
  waypoints.modify.anywhere: { }

  waypoints.teleport.private: { }
  waypoints.teleport.public: { }
  waypoints.teleport.permission: { }

  waypoints.tracking.enabled:
    default: true
  waypoints.tracking.trackAll: { }

  waypoints.updateNotification: { }
